# Generated by Django 4.1.4 on 2022-12-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, choices=[('Alexandria', 'الإسكندرية'), ('North Sinai', 'شمال سيناء'), ('Aswan', 'أسوان'), ('Asyut', 'أسيوط'), ('Beheira', 'البحيرة'), ('Beni Suef', 'بني سويف'), ('Cairo', 'القاهرة'), ('Dakahlia', 'الدقهلية'), ('Damietta', 'دمياط'), ('Fayyoum', 'الفيوم'), ('Gharbiya', 'الغربية'), ('Giza', 'الجيزة'), ('Helwan', 'حلوان'), ('Ismailia', 'الإسماعيلية'), ('Kafr El Sheikh', 'كفرالشيخ'), ('Luxor', 'الأقصر'), ('Marsa Matrouh', 'مرسى مطروح'), ('Minya', 'المنيا'), ('Monofiya', 'المنوفية'), ('New Valley', 'الوادي الجديد'), ('Port Said', 'بورسعيد'), ('Qalioubiya', 'قليويبة'), ('Qena', 'قنا'), ('Red Sea', 'البحر الأحمر'), ('Sharqiya', 'الشرقية'), ('Sohag', 'سوهاج'), ('South Sinai', 'جنوب سيناء'), ('Suez', 'السويس'), ('Tanta', 'طنطا')], max_length=200, null=True),
        ),
    ]
