LOCATIONS = (( "Alexandria", "الإسكندرية"),
( "North Sinai", "شمال سيناء"),
( "Aswan", "أسوان" ),
( "Asyut", "أسيوط" ),
( "Beheira", "البحيرة" ),
( "Beni Suef", "بني سويف" ),
( "Cairo", "القاهرة" ),
( "Dakahlia", "الدقهلية" ),
( "Damietta" , "دمياط" ),
( "Fayyoum", "الفيوم" ),
( "Gharbiya", "الغربية"),
( "Giza", "الجيزة"),
( "Helwan", "حلوان"),
( "Ismailia", "الإسماعيلية"),
( "Kafr El Sheikh", "كفرالشيخ" ),
( "Luxor", "الأقصر"),
( "Marsa Matrouh", "مرسى مطروح" ),
( "Minya", "المنيا"),
( "Monofiya", "المنوفية"),
( "New Valley", "الوادي الجديد"),
( "Port Said", "بورسعيد"),
( "Qalioubiya", "قليويبة"),
( "Qena", "قنا" ),
( "Red Sea", "البحر الأحمر"),
( "Sharqiya", "الشرقية"),
( "Sohag", "سوهاج"),
( "South Sinai", "جنوب سيناء" ),
( "Suez", "السويس"),
( "Tanta", "طنطا"),
)